// Regenerates src/lib/bbr-codelists.ts from the official BBR code lists at teknik.bbr.dk.
// Run: pnpm tsx scripts/update-bbr-codes.ts
import { writeFileSync } from "node:fs";

const LISTS = [
  "BygAnvendelse",
  "EnhAnvendelse",
  "Tagdaekningsmateriale",
  "YdervaeggenesMateriale",
  "BygVarmeinstallation",
  "Opvarmningsmiddel",
  "BygSupplerendeVarme",
  "AsbestholdigtMateriale",
  "Fredning",
  "Oversvoemmelsesselvrisiko",
  "Boligtype",
  "Udlejningsforhold",
  "Toiletforhold",
  "Badeforhold",
  "Koekkenforhold",
  "EtageType",
  "GruAfloebsforhold",
  "GruVandforsyning",
  "Ejerforholdskode",
  "KondemneretBoligenhed",
] as const;

function decode(text: string): string {
  return text
    .replace(/<[^>]+>/g, "")
    .replace(/&#(\d+);/g, (_, n: string) => String.fromCharCode(Number(n)))
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/­/g, "")
    .trim();
}

async function fetchList(name: string): Promise<Record<string, string>> {
  const response = await fetch(`https://teknik.bbr.dk/kodelister/0/1/0/${name}`);
  if (!response.ok) throw new Error(`${name}: HTTP ${response.status}`);
  const html = await response.text();
  const listStart = html.indexOf("kodeliste-list");
  if (listStart < 0) throw new Error(`${name}: code list markup not found`);
  const entries: Record<string, string> = {};
  for (const match of html.slice(listStart).matchAll(/<li>(.*?)<\/li>/gs)) {
    const parsed = decode(match[1] ?? "").match(/^([0-9A-Za-z]+)\s*-\s*(.*)$/s);
    if (parsed) entries[parsed[1]!] = parsed[2]!.replace(/\s+/g, " ").trim();
  }
  if (Object.keys(entries).length === 0) throw new Error(`${name}: no codes parsed`);
  return entries;
}

const lists: Record<string, Record<string, string>> = {};
for (const name of LISTS) {
  lists[name] = await fetchList(name);
  console.error(`${name}: ${Object.keys(lists[name]!).length} codes`);
}

const today = new Date().toISOString().slice(0, 10);
const body = `// Generated by scripts/update-bbr-codes.ts from https://teknik.bbr.dk/kodelister on ${today}.
// Do not edit by hand; rerun the script instead.

export const BBR_CODELISTS = ${JSON.stringify(lists, null, 2)} as const satisfies Record<string, Record<string, string>>;

export type BbrCodelistName = keyof typeof BBR_CODELISTS;
`;
writeFileSync(new URL("../src/lib/bbr-codelists.ts", import.meta.url), body);
console.error("Wrote src/lib/bbr-codelists.ts");
